name: test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  # ランナーで使う環境変数
  USER: tester
  PGPASSWORD: postgres
  DB: postgres

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        # Docker Hubのイメージ
        image: postgres
        # 動かすコンテナで使う環境変数
        env:
          POSTGRES_USER: tester
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    container:
      # runner のイメージ
      # Docker Hubのイメージ
      image: postgres
    steps:
      - name: Hello, world
        run: |
          psql -h postgres -U ${USER} -d ${DB} -c "SELECT 'Hello, world';"
