jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        # Docker Hubのイメージ
        image: postgres
        # 動かすコンテナで使う環境変数
        # この場合はpostgresqlのパスワードを指定している。
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Hello, world
        run: |
          echo "Hello, world"
